const userConfig = [
  {
    name: "name",
    label: "Nombre",
    icon: "face",
  },
  {
    name: "surname",
    label: "Apellido",
    icon: "person",
  },
  {
    name: "DNI",
    label: "DNI",
    icon: "badge",
    type: "numeric",
  },
  {
    name: "course",
    label: "Curso",
    type: "dropdown",
    options: [
      "1-1",
      "1-2",
      "1-3",
      "1-4",
      "2-1",
      "2-2",
      "2-3",
      "2-4",
      "3-1",
      "3-2",
      "3-3",
      "3-4",
      "4-1",
      "4-2",
      "4-3",
      "4-4",
      "5-1",
      "5-2",
      "5-3",
      "5-4",
      "6-1",
      "6-2",
      "6-3",
      "7-1",
      "7-2",
    ],
    icon: "school",
  },
  {
    name: "email",
    label: "Email",
    icon: "mail",
    login: true,
    type: "email-address",
  },
  {
    name: "address",
    label: "Dirección",
    icon: "home",
  },
  {
    name: "password",
    label: "Contraseña",
    login: true,
    icon: "lock",
    secureTextEntry: true,
  },
  {
    name: "phone",
    label: "Telefono",
    icon: "phone",
    type: "phone-pad",
  },
];
export default userConfig;
